# Python: 3.8.2 (tags/v3.8.2:7b3ab59, Feb 25 2020, 23:03:10) [MSC v.1916 64 bit (AMD64)]
# Library: scipy, version: 1.6.2
# Module: scipy.io._test_fortran, version: $Revision: $
import typing

__version__: bytes

def read_unformatted_double(m, n, k, filename) -> typing.Any: ...
def read_unformatted_int(m, n, k, filename) -> typing.Any: ...
def read_unformatted_mixed(m, n, k, filename) -> typing.Any: ...
def __getattr__(name) -> typing.Any: ...
