# Python: 3.8.2 (tags/v3.8.2:7b3ab59, Feb 25 2020, 23:03:10) [MSC v.1916 64 bit (AMD64)]
# Library: scipy, version: 1.6.2
# Module: scipy.stats._stats, version: unspecified
import typing

__pyx_capi__: dict

def __pyx_unpickle_Enum() -> typing.Any: ...

__test__: dict

def _center_distance_matrix() -> typing.Any: ...
def _kendall_dis() -> typing.Any: ...
def _local_correlations() -> typing.Any: ...
def _local_covariance() -> typing.Any: ...
def _rank_distance_matrix() -> typing.Any: ...
def _toint64() -> typing.Any: ...
def _transform_distance_matrix() -> typing.Any: ...
def _weightedrankedtau(x, y, rank, weigher, additive) -> typing.Any: ...
def gaussian_kernel_estimate() -> typing.Any: ...
def geninvgauss_logpdf() -> typing.Any: ...
def von_mises_cdf() -> typing.Any: ...
def __getattr__(name) -> typing.Any: ...
