# Python: 3.8.2 (tags/v3.8.2:7b3ab59, Feb 25 2020, 23:03:10) [MSC v.1916 64 bit (AMD64)]
# Library: scipy, version: 1.6.2
# Module: scipy.stats.mvn, version: $Revision: $
import typing

__version__: bytes

def dkblck() -> typing.Any: ...
def mvndst(lower, upper, infin, correl, maxpts=..., abseps=..., releps=...) -> typing.Any: ...
def mvnun(lower, upper, means, covar, maxpts=..., abseps=..., releps=...) -> typing.Any: ...
def mvnun_weighted(lower, upper, means, weights, covar, maxpts=..., abseps=..., releps=...) -> typing.Any: ...
def __getattr__(name) -> typing.Any: ...
