# Python: 3.8.2 (tags/v3.8.2:7b3ab59, Feb 25 2020, 23:03:10) [MSC v.1916 64 bit (AMD64)]
# Library: scipy, version: 1.6.2
# Module: scipy.cluster._optimal_leaf_ordering, version: unspecified
import typing

def __pyx_unpickle_Enum() -> typing.Any: ...

__test__: dict

def is_valid_dm(D, tol, throw, name, warning) -> typing.Any: ...
def is_valid_y(y, warning, throw, name) -> typing.Any: ...
def optimal_leaf_ordering() -> typing.Any: ...
def squareform(X, force, checks) -> typing.Any: ...
def __getattr__(name) -> typing.Any: ...
