# Python: 3.8.2 (tags/v3.8.2:7b3ab59, Feb 25 2020, 23:03:10) [MSC v.1916 64 bit (AMD64)]
# Library: scipy, version: 1.6.2
# Module: scipy.sparse.linalg.isolve._iterative, version: $Revision: $
import typing

__version__: bytes

def cbicgrevcom(b, x, work, iter, resid, info, ndx1, ndx2, ijob) -> typing.Any: ...
def cbicgstabrevcom(b, x, work, iter, resid, info, ndx1, ndx2, ijob) -> typing.Any: ...
def ccgrevcom(b, x, work, iter, resid, info, ndx1, ndx2, ijob) -> typing.Any: ...
def ccgsrevcom(b, x, work, iter, resid, info, ndx1, ndx2, ijob) -> typing.Any: ...
def cgmresrevcom(b, x, restrt, work, work2, iter, resid, info, ndx1, ndx2, ijob, tol) -> typing.Any: ...
def cqmrrevcom(b, x, work, iter, resid, info, ndx1, ndx2, ijob) -> typing.Any: ...
def dbicgrevcom(b, x, work, iter, resid, info, ndx1, ndx2, ijob) -> typing.Any: ...
def dbicgstabrevcom(b, x, work, iter, resid, info, ndx1, ndx2, ijob) -> typing.Any: ...
def dcgrevcom(b, x, work, iter, resid, info, ndx1, ndx2, ijob) -> typing.Any: ...
def dcgsrevcom(b, x, work, iter, resid, info, ndx1, ndx2, ijob) -> typing.Any: ...
def dgmresrevcom(b, x, restrt, work, work2, iter, resid, info, ndx1, ndx2, ijob, tol) -> typing.Any: ...
def dqmrrevcom(b, x, work, iter, resid, info, ndx1, ndx2, ijob) -> typing.Any: ...
def sbicgrevcom(b, x, work, iter, resid, info, ndx1, ndx2, ijob) -> typing.Any: ...
def sbicgstabrevcom(b, x, work, iter, resid, info, ndx1, ndx2, ijob) -> typing.Any: ...
def scgrevcom(b, x, work, iter, resid, info, ndx1, ndx2, ijob) -> typing.Any: ...
def scgsrevcom(b, x, work, iter, resid, info, ndx1, ndx2, ijob) -> typing.Any: ...
def sgmresrevcom(b, x, restrt, work, work2, iter, resid, info, ndx1, ndx2, ijob, tol) -> typing.Any: ...
def sqmrrevcom(b, x, work, iter, resid, info, ndx1, ndx2, ijob) -> typing.Any: ...
def zbicgrevcom(b, x, work, iter, resid, info, ndx1, ndx2, ijob) -> typing.Any: ...
def zbicgstabrevcom(b, x, work, iter, resid, info, ndx1, ndx2, ijob) -> typing.Any: ...
def zcgrevcom(b, x, work, iter, resid, info, ndx1, ndx2, ijob) -> typing.Any: ...
def zcgsrevcom(b, x, work, iter, resid, info, ndx1, ndx2, ijob) -> typing.Any: ...
def zgmresrevcom(b, x, restrt, work, work2, iter, resid, info, ndx1, ndx2, ijob, tol) -> typing.Any: ...
def zqmrrevcom(b, x, work, iter, resid, info, ndx1, ndx2, ijob) -> typing.Any: ...
def __getattr__(name) -> typing.Any: ...
