# Python: 3.8.2 (tags/v3.8.2:7b3ab59, Feb 25 2020, 23:03:10) [MSC v.1916 64 bit (AMD64)]
# Library: scipy, version: 1.6.2
# Module: scipy.interpolate._bspl, version: unspecified
import typing

def __pyx_unpickle_Enum() -> typing.Any: ...

__test__: dict

def _colloc() -> typing.Any: ...
def _handle_lhs_derivatives() -> typing.Any: ...
def _norm_eq_lsq(x, t, k, y, w, ab, rhs) -> typing.Any: ...
def evaluate_all_bspl() -> typing.Any: ...
def evaluate_spline(t, c, k, xp, nu, extrapolate, out) -> typing.Any: ...
def __getattr__(name) -> typing.Any: ...
