# Python: 3.8.2 (tags/v3.8.2:7b3ab59, Feb 25 2020, 23:03:10) [MSC v.1916 64 bit (AMD64)]
# Library: scipy, version: 1.6.2
# Module: scipy.interpolate._fitpack, version:  1.7
import typing

__version__: str

def _bispev(tx, ty, c, kx, ky, x, y, nux, nuy) -> typing.Any: ...
def _bspldismat(order, xk) -> typing.Any: ...
def _bspleval(xx, xk, coef, k, deriv) -> typing.Any: ...
def _bsplmat(order, xk) -> typing.Any: ...
def _curfit(x, y, w, xb, xe, k, iopt, s, t, nest, wrk, iwrk, per) -> typing.Any: ...
def _insert(iopt, t, c, k, x, m) -> typing.Any: ...
def _parcur(x, w, u, ub, ue, k, iopt, ipar, s, t, nest, wrk, iwrk, per) -> typing.Any: ...
def _spalde(t, c, k, x) -> typing.Any: ...
def _spl_(x, nu, t, c, k, e) -> typing.Any: ...
def _splint(t, c, k, a, b) -> typing.Any: ...
def _sproot(t, c, k, mest) -> typing.Any: ...
def _surfit(x, y, z, w, xb, xe, yb, ye, kx, ky, iopt, s, eps, tx, ty, nxest, nyest, wrk, lwrk1, lwrk2) -> typing.Any: ...
def __getattr__(name) -> typing.Any: ...
