# Python: 3.8.2 (tags/v3.8.2:7b3ab59, Feb 25 2020, 23:03:10) [MSC v.1916 64 bit (AMD64)]
# Library: scipy, version: 1.6.2
# Module: scipy.interpolate._ppoly, version: unspecified
import typing

def __pyx_unpickle_Enum() -> typing.Any: ...

__test__: dict

def _croots_poly1() -> typing.Any: ...
def evaluate(c, x, xp, dx, extrapolate, out) -> typing.Any: ...
def evaluate_bernstein(c, x, xp, nu, extrapolate, out) -> typing.Any: ...
def evaluate_nd(c, xs, ks, xp, dx, extrapolate, out) -> typing.Any: ...
def fix_continuity(c, x, order) -> typing.Any: ...
def integrate(c, x, a, b, extrapolate, out) -> typing.Any: ...
def real_roots() -> typing.Any: ...
def __getattr__(name) -> typing.Any: ...
