# Python: 3.8.2 (tags/v3.8.2:7b3ab59, Feb 25 2020, 23:03:10) [MSC v.1916 64 bit (AMD64)]
# Library: scipy, version: 1.6.2
# Module: scipy._lib._ccallback_c, version: unspecified
import typing

__pyx_capi__: dict
__test__: dict

def check_capsule(item) -> typing.Any: ...
def get_capsule_signature() -> typing.Any: ...
def get_raw_capsule(ptr, name, context) -> typing.Any: ...

idx: int

def plus1_ctypes() -> typing.Any: ...
def plus1b_ctypes() -> typing.Any: ...
def plus1bc_ctypes() -> typing.Any: ...

sig: tuple
sigs: list

def sine_ctypes() -> typing.Any: ...
def test_call_cython() -> typing.Any: ...
def __getattr__(name) -> typing.Any: ...
