# Python: 3.8.2 (tags/v3.8.2:7b3ab59, Feb 25 2020, 23:03:10) [MSC v.1916 64 bit (AMD64)]
# Library: scipy, version: 1.6.2
# Module: scipy.sparse._csparsetools, version: unspecified
import typing

def __pyx_unpickle_Enum() -> typing.Any: ...

__test__: dict

def _lil_fancy_get_int32() -> typing.Any: ...
def _lil_fancy_get_int64() -> typing.Any: ...
def _lil_fancy_set_int32_bool_() -> typing.Any: ...
def _lil_fancy_set_int32_clongdouble() -> typing.Any: ...
def _lil_fancy_set_int32_complex128() -> typing.Any: ...
def _lil_fancy_set_int32_complex64() -> typing.Any: ...
def _lil_fancy_set_int32_float32() -> typing.Any: ...
def _lil_fancy_set_int32_float64() -> typing.Any: ...
def _lil_fancy_set_int32_int16() -> typing.Any: ...
def _lil_fancy_set_int32_int32() -> typing.Any: ...
def _lil_fancy_set_int32_int64() -> typing.Any: ...
def _lil_fancy_set_int32_int8() -> typing.Any: ...
def _lil_fancy_set_int32_longdouble() -> typing.Any: ...
def _lil_fancy_set_int32_uint16() -> typing.Any: ...
def _lil_fancy_set_int32_uint32() -> typing.Any: ...
def _lil_fancy_set_int32_uint64() -> typing.Any: ...
def _lil_fancy_set_int32_uint8() -> typing.Any: ...
def _lil_fancy_set_int64_bool_() -> typing.Any: ...
def _lil_fancy_set_int64_clongdouble() -> typing.Any: ...
def _lil_fancy_set_int64_complex128() -> typing.Any: ...
def _lil_fancy_set_int64_complex64() -> typing.Any: ...
def _lil_fancy_set_int64_float32() -> typing.Any: ...
def _lil_fancy_set_int64_float64() -> typing.Any: ...
def _lil_fancy_set_int64_int16() -> typing.Any: ...
def _lil_fancy_set_int64_int32() -> typing.Any: ...
def _lil_fancy_set_int64_int64() -> typing.Any: ...
def _lil_fancy_set_int64_int8() -> typing.Any: ...
def _lil_fancy_set_int64_longdouble() -> typing.Any: ...
def _lil_fancy_set_int64_uint16() -> typing.Any: ...
def _lil_fancy_set_int64_uint32() -> typing.Any: ...
def _lil_fancy_set_int64_uint64() -> typing.Any: ...
def _lil_fancy_set_int64_uint8() -> typing.Any: ...
def _lil_flatten_to_array_bool_() -> typing.Any: ...
def _lil_flatten_to_array_clongdouble() -> typing.Any: ...
def _lil_flatten_to_array_complex128() -> typing.Any: ...
def _lil_flatten_to_array_complex64() -> typing.Any: ...
def _lil_flatten_to_array_float32() -> typing.Any: ...
def _lil_flatten_to_array_float64() -> typing.Any: ...
def _lil_flatten_to_array_int16() -> typing.Any: ...
def _lil_flatten_to_array_int32() -> typing.Any: ...
def _lil_flatten_to_array_int64() -> typing.Any: ...
def _lil_flatten_to_array_int8() -> typing.Any: ...
def _lil_flatten_to_array_longdouble() -> typing.Any: ...
def _lil_flatten_to_array_uint16() -> typing.Any: ...
def _lil_flatten_to_array_uint32() -> typing.Any: ...
def _lil_flatten_to_array_uint64() -> typing.Any: ...
def _lil_flatten_to_array_uint8() -> typing.Any: ...
def _lil_get_lengths_int32() -> typing.Any: ...
def _lil_get_lengths_int64() -> typing.Any: ...
def lil_fancy_get() -> typing.Any: ...
def lil_fancy_set() -> typing.Any: ...
def lil_flatten_to_array() -> typing.Any: ...
def lil_get1() -> typing.Any: ...
def lil_get_lengths() -> typing.Any: ...
def lil_get_row_ranges() -> typing.Any: ...
def lil_insert() -> typing.Any: ...
def __getattr__(name) -> typing.Any: ...
