# Python: 3.8.2 (tags/v3.8.2:7b3ab59, Feb 25 2020, 23:03:10) [MSC v.1916 64 bit (AMD64)]
# Library: scipy, version: 1.6.2
# Module: scipy.fft._pocketfft.pypocketfft, version: unspecified
import typing

def c2c(a, axes=..., forward=..., inorm=..., out=..., nthreads=...) -> typing.Any: ...
def c2r(a, axes=..., lastsize=..., forward=..., inorm=..., out=..., nthreads=...) -> typing.Any: ...
def dct(a, type, axes=..., inorm=..., out=..., nthreads=...) -> typing.Any: ...
def dst(a, type, axes=..., inorm=..., out=..., nthreads=...) -> typing.Any: ...
def genuine_hartley(a, axes=..., inorm=..., out=..., nthreads=...) -> typing.Any: ...
def good_size() -> typing.Any: ...
def r2c(a, axes=..., forward=..., inorm=..., out=..., nthreads=...) -> typing.Any: ...
def r2r_fftpack(a, axes, real2hermitian, forward, inorm=..., out=..., nthreads=...) -> typing.Any: ...
def separable_hartley(a, axes=..., inorm=..., out=..., nthreads=...) -> typing.Any: ...
def __getattr__(name) -> typing.Any: ...
