from setuptools.command.build_ext import customize_compiler as customize_compiler, new_compiler as new_compiler

def compile_test_program(code, extra_preargs: list = [], extra_postargs: list = []) -> None: ...
def basic_check_build() -> None: ...
