# Python: 3.8.2 (tags/v3.8.2:7b3ab59, Feb 25 2020, 23:03:10) [MSC v.1916 64 bit (AMD64)]
# Library: scipy, version: 1.6.2
# Module: scipy.sparse.csgraph._flow, version: unspecified
import builtins as _mod_builtins
import typing

import numpy as _mod_numpy

DTYPE = _mod_numpy.float64
ITYPE = _mod_numpy.int32

class MaximumFlowResult(_mod_builtins.object):
    __dict__: dict[str, typing.Any]
    def __init__(self, flow_value, residual) -> None: ...
    @classmethod
    def __init_subclass__(cls) -> None: ...
    __module__: str
    @classmethod
    def __subclasshook__(cls, subclass: typing.Any) -> bool: ...
    @property
    def __weakref__(self) -> typing.Any: ...
    def __getattr__(self, name) -> typing.Any: ...

def __pyx_unpickle_Enum() -> typing.Any: ...

__test__: dict

def _add_reverse_edges() -> typing.Any: ...
def _make_edge_pointers() -> typing.Any: ...
def isspmatrix_csr(x) -> typing.Any: ...
def maximum_flow(csgraph, source, sink) -> typing.Any: ...
def __getattr__(name) -> typing.Any: ...
