# Python: 3.8.2 (tags/v3.8.2:7b3ab59, Feb 25 2020, 23:03:10) [MSC v.1916 64 bit (AMD64)]
# Library: scipy, version: 1.6.2
# Module: scipy.sparse.csgraph._matching, version: unspecified
import typing

import numpy as _mod_numpy

BTYPE = _mod_numpy.uint8
DTYPE = _mod_numpy.float64
ITYPE = _mod_numpy.int32

def __pyx_unpickle_Enum() -> typing.Any: ...

__test__: dict

def isspmatrix_coo(x) -> typing.Any: ...
def isspmatrix_csc(x) -> typing.Any: ...
def isspmatrix_csr(x) -> typing.Any: ...
def maximum_bipartite_matching(graph, perm_type=...) -> typing.Any: ...
def min_weight_full_bipartite_matching(biadjacency_matrix, maximize=...) -> typing.Any: ...
def __getattr__(name) -> typing.Any: ...
