# Python: 3.8.2 (tags/v3.8.2:7b3ab59, Feb 25 2020, 23:03:10) [MSC v.1916 64 bit (AMD64)]
# Library: scipy, version: 1.6.2
# Module: scipy.sparse.csgraph._tools, version: unspecified
import typing

import numpy as _mod_numpy

DTYPE = _mod_numpy.float64
ITYPE = _mod_numpy.int32

__test__: dict

def construct_dist_matrix(graph, predecessors, directed=..., null_value=...) -> typing.Any: ...
def csgraph_from_dense(graph, null_value=..., nan_null=..., infinity_null=...) -> typing.Any: ...
def csgraph_from_masked(graph) -> typing.Any: ...
def csgraph_masked_from_dense(graph, null_value=..., nan_null=..., infinity_null=..., copy=...) -> typing.Any: ...
def csgraph_to_dense(csgraph, null_value=...) -> typing.Any: ...
def csgraph_to_masked(csgraph) -> typing.Any: ...
def isspmatrix(x) -> typing.Any: ...
def isspmatrix_csc(x) -> typing.Any: ...
def isspmatrix_csr(x) -> typing.Any: ...
def isspmatrix_lil(x) -> typing.Any: ...
def reconstruct_path(csgraph, predecessors, directed=...) -> typing.Any: ...
def __getattr__(name) -> typing.Any: ...
