# Python: 3.8.2 (tags/v3.8.2:7b3ab59, Feb 25 2020, 23:03:10) [MSC v.1916 64 bit (AMD64)]
# Library: scipy, version: 1.6.2
# Module: scipy.sparse.csgraph._traversal, version: unspecified
import typing

import numpy as _mod_numpy

DTYPE = _mod_numpy.float64
ITYPE = _mod_numpy.int32

__test__: dict

def breadth_first_order(csgraph, i_start, directed=..., return_predecessors=...) -> typing.Any: ...
def breadth_first_tree(csgraph, i_start, directed=...) -> typing.Any: ...
def connected_components(csgraph, directed=..., connection=..., return_labels=...) -> typing.Any: ...
def depth_first_order(csgraph, i_start, directed=..., return_predecessors=...) -> typing.Any: ...
def depth_first_tree(csgraph, i_start, directed=...) -> typing.Any: ...
def isspmatrix(x) -> typing.Any: ...
def isspmatrix_csc(x) -> typing.Any: ...
def isspmatrix_csr(x) -> typing.Any: ...
def reconstruct_path(csgraph, predecessors, directed=...) -> typing.Any: ...
def validate_graph(
    csgraph,
    directed,
    dtype,
    csr_output,
    dense_output,
    copy_if_dense,
    copy_if_sparse,
    null_value_in,
    null_value_out,
    infinity_null,
    nan_null,
) -> typing.Any: ...
def __getattr__(name) -> typing.Any: ...
