# Python: 3.8.2 (tags/v3.8.2:7b3ab59, Feb 25 2020, 23:03:10) [MSC v.1916 64 bit (AMD64)]
# Library: scipy, version: 1.6.2
# Module: scipy.signal._peak_finding_utils, version: unspecified
import builtins as _mod_builtins
import typing

class PeakPropertyWarning(_mod_builtins.RuntimeWarning):
    __dict__: dict[str, typing.Any]
    def __init__(self, *args, **kwargs) -> None: ...
    @classmethod
    def __init_subclass__(cls) -> None: ...
    __module__: str
    @classmethod
    def __subclasshook__(cls, subclass: typing.Any) -> bool: ...
    @property
    def __weakref__(self) -> typing.Any: ...
    def __getattr__(self, name) -> typing.Any: ...

def __pyx_unpickle_Enum() -> typing.Any: ...

__test__: dict

def _local_maxima_1d() -> typing.Any: ...
def _peak_prominences() -> typing.Any: ...
def _peak_widths() -> typing.Any: ...
def _select_by_peak_distance() -> typing.Any: ...
def __getattr__(name) -> typing.Any: ...
