# Python: 3.8.2 (tags/v3.8.2:7b3ab59, Feb 25 2020, 23:03:10) [MSC v.1916 64 bit (AMD64)]
# Library: scipy, version: 1.6.2
# Module: scipy.signal._upfirdn_apply, version: unspecified
import typing

def __pyx_unpickle_Enum() -> typing.Any: ...

__test__: dict

def _apply(data, h_trans_flip, out, up, down, axis, mode, cval) -> typing.Any: ...
def _output_len() -> typing.Any: ...
def _pad_test() -> typing.Any: ...
def mode_enum() -> typing.Any: ...
def __getattr__(name) -> typing.Any: ...
