# Python: 3.8.2 (tags/v3.8.2:7b3ab59, Feb 25 2020, 23:03:10) [MSC v.1916 64 bit (AMD64)]
# Library: scipy, version: 1.6.2
# Module: scipy.signal.spline, version: 0.2
import typing

__version__: str

def cspline2d(input, lambda_=..., precision=...) -> typing.Any: ...
def qspline2d(input, lambda_=..., precision=...) -> typing.Any: ...
def sepfir2d(input, hrow, hcol) -> typing.Any: ...
def symiirorder1(input, c0, z1, precision=...) -> typing.Any: ...
def symiirorder2(input, r, omega, precision=...) -> typing.Any: ...
def __getattr__(name) -> typing.Any: ...
