# Python: 3.8.2 (tags/v3.8.2:7b3ab59, Feb 25 2020, 23:03:10) [MSC v.1916 64 bit (AMD64)]
# Library: scipy, version: 1.6.2
# Module: scipy.linalg._fblas, version: $Revision: $
import typing

__version__: bytes

def caxpy(x, y, n=..., a=..., offx=..., incx=..., offy=..., incy=...) -> typing.Any: ...
def ccopy(x, y, n=..., offx=..., incx=..., offy=..., incy=...) -> typing.Any: ...
def cdotc(x, y, n=..., offx=..., incx=..., offy=..., incy=...) -> typing.Any: ...
def cdotu(x, y, n=..., offx=..., incx=..., offy=..., incy=...) -> typing.Any: ...
def cgbmv(
    m, n, kl, ku, alpha, a, x, incx=..., offx=..., beta=..., y=..., incy=..., offy=..., trans=..., overwrite_y=...
) -> typing.Any: ...
def cgemm(alpha, a, b, beta=..., c=..., trans_a=..., trans_b=..., overwrite_c=...) -> typing.Any: ...
def cgemv(alpha, a, x, beta=..., y=..., offx=..., incx=..., offy=..., incy=..., trans=..., overwrite_y=...) -> typing.Any: ...
def cgerc(alpha, x, y, incx=..., incy=..., a=..., overwrite_x=..., overwrite_y=..., overwrite_a=...) -> typing.Any: ...
def cgeru(alpha, x, y, incx=..., incy=..., a=..., overwrite_x=..., overwrite_y=..., overwrite_a=...) -> typing.Any: ...
def chbmv(k, alpha, a, x, incx=..., offx=..., beta=..., y=..., incy=..., offy=..., lower=..., overwrite_y=...) -> typing.Any: ...
def chemm(alpha, a, b, beta=..., c=..., side=..., lower=..., overwrite_c=...) -> typing.Any: ...
def chemv(alpha, a, x, beta=..., y=..., offx=..., incx=..., offy=..., incy=..., lower=..., overwrite_y=...) -> typing.Any: ...
def cher(alpha, x, lower=..., incx=..., offx=..., n=..., a=..., overwrite_a=...) -> typing.Any: ...
def cher2(alpha, x, y, lower=..., incx=..., offx=..., incy=..., offy=..., n=..., a=..., overwrite_a=...) -> typing.Any: ...
def cher2k(alpha, a, b, beta=..., c=..., trans=..., lower=..., overwrite_c=...) -> typing.Any: ...
def cherk(alpha, a, beta=..., c=..., trans=..., lower=..., overwrite_c=...) -> typing.Any: ...
def chpmv(n, alpha, ap, x, incx=..., offx=..., beta=..., y=..., incy=..., offy=..., lower=..., overwrite_y=...) -> typing.Any: ...
def chpr(n, alpha, x, ap, incx=..., offx=..., lower=..., overwrite_ap=...) -> typing.Any: ...
def chpr2(n, alpha, x, y, ap, incx=..., offx=..., incy=..., offy=..., lower=..., overwrite_ap=...) -> typing.Any: ...
def crotg(a, b) -> typing.Any: ...
def cscal(a, x, n=..., offx=..., incx=...) -> typing.Any: ...
def cspmv(n, alpha, ap, x, incx=..., offx=..., beta=..., y=..., incy=..., offy=..., lower=..., overwrite_y=...) -> typing.Any: ...
def cspr(n, alpha, x, ap, incx=..., offx=..., lower=..., overwrite_ap=...) -> typing.Any: ...
def csrot(x, y, c, s, n=..., offx=..., incx=..., offy=..., incy=..., overwrite_x=..., overwrite_y=...) -> typing.Any: ...
def csscal(a, x, n=..., offx=..., incx=..., overwrite_x=...) -> typing.Any: ...
def cswap(x, y, n=..., offx=..., incx=..., offy=..., incy=...) -> typing.Any: ...
def csymm(alpha, a, b, beta=..., c=..., side=..., lower=..., overwrite_c=...) -> typing.Any: ...
def csyr(alpha, x, lower=..., incx=..., offx=..., n=..., a=..., overwrite_a=...) -> typing.Any: ...
def csyr2k(alpha, a, b, beta=..., c=..., trans=..., lower=..., overwrite_c=...) -> typing.Any: ...
def csyrk(alpha, a, beta=..., c=..., trans=..., lower=..., overwrite_c=...) -> typing.Any: ...
def ctbmv(k, a, x, incx=..., offx=..., lower=..., trans=..., diag=..., overwrite_x=...) -> typing.Any: ...
def ctbsv(k, a, x, incx=..., offx=..., lower=..., trans=..., diag=..., overwrite_x=...) -> typing.Any: ...
def ctpmv(n, ap, x, incx=..., offx=..., lower=..., trans=..., diag=..., overwrite_x=...) -> typing.Any: ...
def ctpsv(n, ap, x, incx=..., offx=..., lower=..., trans=..., diag=..., overwrite_x=...) -> typing.Any: ...
def ctrmm(alpha, a, b, side=..., lower=..., trans_a=..., diag=..., overwrite_b=...) -> typing.Any: ...
def ctrmv(a, x, offx=..., incx=..., lower=..., trans=..., diag=..., overwrite_x=...) -> typing.Any: ...
def ctrsm(alpha, a, b, side=..., lower=..., trans_a=..., diag=..., overwrite_b=...) -> typing.Any: ...
def ctrsv(a, x, incx=..., offx=..., lower=..., trans=..., diag=..., overwrite_x=...) -> typing.Any: ...
def dasum(x, n=..., offx=..., incx=...) -> typing.Any: ...
def daxpy(x, y, n=..., a=..., offx=..., incx=..., offy=..., incy=...) -> typing.Any: ...
def dcopy(x, y, n=..., offx=..., incx=..., offy=..., incy=...) -> typing.Any: ...
def ddot(x, y, n=..., offx=..., incx=..., offy=..., incy=...) -> typing.Any: ...
def dgbmv(
    m, n, kl, ku, alpha, a, x, incx=..., offx=..., beta=..., y=..., incy=..., offy=..., trans=..., overwrite_y=...
) -> typing.Any: ...
def dgemm(alpha, a, b, beta=..., c=..., trans_a=..., trans_b=..., overwrite_c=...) -> typing.Any: ...
def dgemv(alpha, a, x, beta=..., y=..., offx=..., incx=..., offy=..., incy=..., trans=..., overwrite_y=...) -> typing.Any: ...
def dger(alpha, x, y, incx=..., incy=..., a=..., overwrite_x=..., overwrite_y=..., overwrite_a=...) -> typing.Any: ...
def dnrm2(x, n=..., offx=..., incx=...) -> typing.Any: ...
def drot(x, y, c, s, n=..., offx=..., incx=..., offy=..., incy=..., overwrite_x=..., overwrite_y=...) -> typing.Any: ...
def drotg(a, b) -> typing.Any: ...
def drotm(x, y, param, n=..., offx=..., incx=..., offy=..., incy=..., overwrite_x=..., overwrite_y=...) -> typing.Any: ...
def drotmg(d1, d2, x1, y1) -> typing.Any: ...
def dsbmv(k, alpha, a, x, incx=..., offx=..., beta=..., y=..., incy=..., offy=..., lower=..., overwrite_y=...) -> typing.Any: ...
def dscal(a, x, n=..., offx=..., incx=...) -> typing.Any: ...
def dspmv(n, alpha, ap, x, incx=..., offx=..., beta=..., y=..., incy=..., offy=..., lower=..., overwrite_y=...) -> typing.Any: ...
def dspr(n, alpha, x, ap, incx=..., offx=..., lower=..., overwrite_ap=...) -> typing.Any: ...
def dspr2(n, alpha, x, y, ap, incx=..., offx=..., incy=..., offy=..., lower=..., overwrite_ap=...) -> typing.Any: ...
def dswap(x, y, n=..., offx=..., incx=..., offy=..., incy=...) -> typing.Any: ...
def dsymm(alpha, a, b, beta=..., c=..., side=..., lower=..., overwrite_c=...) -> typing.Any: ...
def dsymv(alpha, a, x, beta=..., y=..., offx=..., incx=..., offy=..., incy=..., lower=..., overwrite_y=...) -> typing.Any: ...
def dsyr(alpha, x, lower=..., incx=..., offx=..., n=..., a=..., overwrite_a=...) -> typing.Any: ...
def dsyr2(alpha, x, y, lower=..., incx=..., offx=..., incy=..., offy=..., n=..., a=..., overwrite_a=...) -> typing.Any: ...
def dsyr2k(alpha, a, b, beta=..., c=..., trans=..., lower=..., overwrite_c=...) -> typing.Any: ...
def dsyrk(alpha, a, beta=..., c=..., trans=..., lower=..., overwrite_c=...) -> typing.Any: ...
def dtbmv(k, a, x, incx=..., offx=..., lower=..., trans=..., diag=..., overwrite_x=...) -> typing.Any: ...
def dtbsv(k, a, x, incx=..., offx=..., lower=..., trans=..., diag=..., overwrite_x=...) -> typing.Any: ...
def dtpmv(n, ap, x, incx=..., offx=..., lower=..., trans=..., diag=..., overwrite_x=...) -> typing.Any: ...
def dtpsv(n, ap, x, incx=..., offx=..., lower=..., trans=..., diag=..., overwrite_x=...) -> typing.Any: ...
def dtrmm(alpha, a, b, side=..., lower=..., trans_a=..., diag=..., overwrite_b=...) -> typing.Any: ...
def dtrmv(a, x, offx=..., incx=..., lower=..., trans=..., diag=..., overwrite_x=...) -> typing.Any: ...
def dtrsm(alpha, a, b, side=..., lower=..., trans_a=..., diag=..., overwrite_b=...) -> typing.Any: ...
def dtrsv(a, x, incx=..., offx=..., lower=..., trans=..., diag=..., overwrite_x=...) -> typing.Any: ...
def dzasum(x, n=..., offx=..., incx=...) -> typing.Any: ...
def dznrm2(x, n=..., offx=..., incx=...) -> typing.Any: ...
def icamax(x, n=..., offx=..., incx=...) -> typing.Any: ...
def idamax(x, n=..., offx=..., incx=...) -> typing.Any: ...
def isamax(x, n=..., offx=..., incx=...) -> typing.Any: ...
def izamax(x, n=..., offx=..., incx=...) -> typing.Any: ...
def sasum(x, n=..., offx=..., incx=...) -> typing.Any: ...
def saxpy(x, y, n=..., a=..., offx=..., incx=..., offy=..., incy=...) -> typing.Any: ...
def scasum(x, n=..., offx=..., incx=...) -> typing.Any: ...
def scnrm2(x, n=..., offx=..., incx=...) -> typing.Any: ...
def scopy(x, y, n=..., offx=..., incx=..., offy=..., incy=...) -> typing.Any: ...
def sdot(x, y, n=..., offx=..., incx=..., offy=..., incy=...) -> typing.Any: ...
def sgbmv(
    m, n, kl, ku, alpha, a, x, incx=..., offx=..., beta=..., y=..., incy=..., offy=..., trans=..., overwrite_y=...
) -> typing.Any: ...
def sgemm(alpha, a, b, beta=..., c=..., trans_a=..., trans_b=..., overwrite_c=...) -> typing.Any: ...
def sgemv(alpha, a, x, beta=..., y=..., offx=..., incx=..., offy=..., incy=..., trans=..., overwrite_y=...) -> typing.Any: ...
def sger(alpha, x, y, incx=..., incy=..., a=..., overwrite_x=..., overwrite_y=..., overwrite_a=...) -> typing.Any: ...
def snrm2(x, n=..., offx=..., incx=...) -> typing.Any: ...
def srot(x, y, c, s, n=..., offx=..., incx=..., offy=..., incy=..., overwrite_x=..., overwrite_y=...) -> typing.Any: ...
def srotg(a, b) -> typing.Any: ...
def srotm(x, y, param, n=..., offx=..., incx=..., offy=..., incy=..., overwrite_x=..., overwrite_y=...) -> typing.Any: ...
def srotmg(d1, d2, x1, y1) -> typing.Any: ...
def ssbmv(k, alpha, a, x, incx=..., offx=..., beta=..., y=..., incy=..., offy=..., lower=..., overwrite_y=...) -> typing.Any: ...
def sscal(a, x, n=..., offx=..., incx=...) -> typing.Any: ...
def sspmv(n, alpha, ap, x, incx=..., offx=..., beta=..., y=..., incy=..., offy=..., lower=..., overwrite_y=...) -> typing.Any: ...
def sspr(n, alpha, x, ap, incx=..., offx=..., lower=..., overwrite_ap=...) -> typing.Any: ...
def sspr2(n, alpha, x, y, ap, incx=..., offx=..., incy=..., offy=..., lower=..., overwrite_ap=...) -> typing.Any: ...
def sswap(x, y, n=..., offx=..., incx=..., offy=..., incy=...) -> typing.Any: ...
def ssymm(alpha, a, b, beta=..., c=..., side=..., lower=..., overwrite_c=...) -> typing.Any: ...
def ssymv(alpha, a, x, beta=..., y=..., offx=..., incx=..., offy=..., incy=..., lower=..., overwrite_y=...) -> typing.Any: ...
def ssyr(alpha, x, lower=..., incx=..., offx=..., n=..., a=..., overwrite_a=...) -> typing.Any: ...
def ssyr2(alpha, x, y, lower=..., incx=..., offx=..., incy=..., offy=..., n=..., a=..., overwrite_a=...) -> typing.Any: ...
def ssyr2k(alpha, a, b, beta=..., c=..., trans=..., lower=..., overwrite_c=...) -> typing.Any: ...
def ssyrk(alpha, a, beta=..., c=..., trans=..., lower=..., overwrite_c=...) -> typing.Any: ...
def stbmv(k, a, x, incx=..., offx=..., lower=..., trans=..., diag=..., overwrite_x=...) -> typing.Any: ...
def stbsv(k, a, x, incx=..., offx=..., lower=..., trans=..., diag=..., overwrite_x=...) -> typing.Any: ...
def stpmv(n, ap, x, incx=..., offx=..., lower=..., trans=..., diag=..., overwrite_x=...) -> typing.Any: ...
def stpsv(n, ap, x, incx=..., offx=..., lower=..., trans=..., diag=..., overwrite_x=...) -> typing.Any: ...
def strmm(alpha, a, b, side=..., lower=..., trans_a=..., diag=..., overwrite_b=...) -> typing.Any: ...
def strmv(a, x, offx=..., incx=..., lower=..., trans=..., diag=..., overwrite_x=...) -> typing.Any: ...
def strsm(alpha, a, b, side=..., lower=..., trans_a=..., diag=..., overwrite_b=...) -> typing.Any: ...
def strsv(a, x, incx=..., offx=..., lower=..., trans=..., diag=..., overwrite_x=...) -> typing.Any: ...
def zaxpy(x, y, n=..., a=..., offx=..., incx=..., offy=..., incy=...) -> typing.Any: ...
def zcopy(x, y, n=..., offx=..., incx=..., offy=..., incy=...) -> typing.Any: ...
def zdotc(x, y, n=..., offx=..., incx=..., offy=..., incy=...) -> typing.Any: ...
def zdotu(x, y, n=..., offx=..., incx=..., offy=..., incy=...) -> typing.Any: ...
def zdrot(x, y, c, s, n=..., offx=..., incx=..., offy=..., incy=..., overwrite_x=..., overwrite_y=...) -> typing.Any: ...
def zdscal(a, x, n=..., offx=..., incx=..., overwrite_x=...) -> typing.Any: ...
def zgbmv(
    m, n, kl, ku, alpha, a, x, incx=..., offx=..., beta=..., y=..., incy=..., offy=..., trans=..., overwrite_y=...
) -> typing.Any: ...
def zgemm(alpha, a, b, beta=..., c=..., trans_a=..., trans_b=..., overwrite_c=...) -> typing.Any: ...
def zgemv(alpha, a, x, beta=..., y=..., offx=..., incx=..., offy=..., incy=..., trans=..., overwrite_y=...) -> typing.Any: ...
def zgerc(alpha, x, y, incx=..., incy=..., a=..., overwrite_x=..., overwrite_y=..., overwrite_a=...) -> typing.Any: ...
def zgeru(alpha, x, y, incx=..., incy=..., a=..., overwrite_x=..., overwrite_y=..., overwrite_a=...) -> typing.Any: ...
def zhbmv(k, alpha, a, x, incx=..., offx=..., beta=..., y=..., incy=..., offy=..., lower=..., overwrite_y=...) -> typing.Any: ...
def zhemm(alpha, a, b, beta=..., c=..., side=..., lower=..., overwrite_c=...) -> typing.Any: ...
def zhemv(alpha, a, x, beta=..., y=..., offx=..., incx=..., offy=..., incy=..., lower=..., overwrite_y=...) -> typing.Any: ...
def zher(alpha, x, lower=..., incx=..., offx=..., n=..., a=..., overwrite_a=...) -> typing.Any: ...
def zher2(alpha, x, y, lower=..., incx=..., offx=..., incy=..., offy=..., n=..., a=..., overwrite_a=...) -> typing.Any: ...
def zher2k(alpha, a, b, beta=..., c=..., trans=..., lower=..., overwrite_c=...) -> typing.Any: ...
def zherk(alpha, a, beta=..., c=..., trans=..., lower=..., overwrite_c=...) -> typing.Any: ...
def zhpmv(n, alpha, ap, x, incx=..., offx=..., beta=..., y=..., incy=..., offy=..., lower=..., overwrite_y=...) -> typing.Any: ...
def zhpr(n, alpha, x, ap, incx=..., offx=..., lower=..., overwrite_ap=...) -> typing.Any: ...
def zhpr2(n, alpha, x, y, ap, incx=..., offx=..., incy=..., offy=..., lower=..., overwrite_ap=...) -> typing.Any: ...
def zrotg(a, b) -> typing.Any: ...
def zscal(a, x, n=..., offx=..., incx=...) -> typing.Any: ...
def zspmv(n, alpha, ap, x, incx=..., offx=..., beta=..., y=..., incy=..., offy=..., lower=..., overwrite_y=...) -> typing.Any: ...
def zspr(n, alpha, x, ap, incx=..., offx=..., lower=..., overwrite_ap=...) -> typing.Any: ...
def zswap(x, y, n=..., offx=..., incx=..., offy=..., incy=...) -> typing.Any: ...
def zsymm(alpha, a, b, beta=..., c=..., side=..., lower=..., overwrite_c=...) -> typing.Any: ...
def zsyr(alpha, x, lower=..., incx=..., offx=..., n=..., a=..., overwrite_a=...) -> typing.Any: ...
def zsyr2k(alpha, a, b, beta=..., c=..., trans=..., lower=..., overwrite_c=...) -> typing.Any: ...
def zsyrk(alpha, a, beta=..., c=..., trans=..., lower=..., overwrite_c=...) -> typing.Any: ...
def ztbmv(k, a, x, incx=..., offx=..., lower=..., trans=..., diag=..., overwrite_x=...) -> typing.Any: ...
def ztbsv(k, a, x, incx=..., offx=..., lower=..., trans=..., diag=..., overwrite_x=...) -> typing.Any: ...
def ztpmv(n, ap, x, incx=..., offx=..., lower=..., trans=..., diag=..., overwrite_x=...) -> typing.Any: ...
def ztpsv(n, ap, x, incx=..., offx=..., lower=..., trans=..., diag=..., overwrite_x=...) -> typing.Any: ...
def ztrmm(alpha, a, b, side=..., lower=..., trans_a=..., diag=..., overwrite_b=...) -> typing.Any: ...
def ztrmv(a, x, offx=..., incx=..., lower=..., trans=..., diag=..., overwrite_x=...) -> typing.Any: ...
def ztrsm(alpha, a, b, side=..., lower=..., trans_a=..., diag=..., overwrite_b=...) -> typing.Any: ...
def ztrsv(a, x, incx=..., offx=..., lower=..., trans=..., diag=..., overwrite_x=...) -> typing.Any: ...
def __getattr__(name) -> typing.Any: ...
