# Python: 3.8.2 (tags/v3.8.2:7b3ab59, Feb 25 2020, 23:03:10) [MSC v.1916 64 bit (AMD64)]
# Library: scipy, version: 1.6.2
# Module: scipy.linalg._flinalg, version: $Revision: $
import typing

__version__: bytes

def cdet_c(a, overwrite_a=...) -> typing.Any: ...
def cdet_r(a, overwrite_a=...) -> typing.Any: ...
def clu_c(a, permute_l=..., overwrite_a=...) -> typing.Any: ...
def ddet_c(a, overwrite_a=...) -> typing.Any: ...
def ddet_r(a, overwrite_a=...) -> typing.Any: ...
def dlu_c(a, permute_l=..., overwrite_a=...) -> typing.Any: ...
def sdet_c(a, overwrite_a=...) -> typing.Any: ...
def sdet_r(a, overwrite_a=...) -> typing.Any: ...
def slu_c(a, permute_l=..., overwrite_a=...) -> typing.Any: ...
def zdet_c(a, overwrite_a=...) -> typing.Any: ...
def zdet_r(a, overwrite_a=...) -> typing.Any: ...
def zlu_c(a, permute_l=..., overwrite_a=...) -> typing.Any: ...
def __getattr__(name) -> typing.Any: ...
