version = "1.3.*"
upstream_repository = "https://github.com/scikit-learn/scikit-learn"
requires_python=">=3.9"
requires=[
    "Cython",
    "setuptools",
    "matplotlib>=3.8",
    "numpy>=1.20",
    "scipy",
    "pandas",
    "pandas-stubs",
]
