# Python: 3.8.2 (tags/v3.8.2:7b3ab59, Feb 25 2020, 23:03:10) [MSC v.1916 64 bit (AMD64)]
# Library: scipy, version: 1.6.2
# Module: scipy.special._test_round, version: unspecified
import typing

def __pyx_unpickle_Enum() -> typing.Any: ...

__test__: dict

def assert_(val, msg) -> typing.Any: ...
def have_fenv() -> typing.Any: ...
def random_double() -> typing.Any: ...
def test_add_round() -> typing.Any: ...
def __getattr__(name) -> typing.Any: ...
