# Python: 3.8.2 (tags/v3.8.2:7b3ab59, Feb 25 2020, 23:03:10) [MSC v.1916 64 bit (AMD64)]
# Library: scipy, version: 1.6.2
# Module: scipy.special._ufuncs, version: unspecified
import builtins as _mod_builtins
import typing

__test__: dict

def _cospi(x, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...) -> typing.Any: ...
def _ellip_harm(
    x1, x2, x3, x4, x5, x6, x7, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...
) -> typing.Any: ...
def _factorial(
    x, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...
) -> typing.Any: ...
def _igam_fac(
    x1, x2, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...
) -> typing.Any: ...
def _kolmogc(x, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...) -> typing.Any: ...
def _kolmogci(
    x, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...
) -> typing.Any: ...
def _kolmogp(x, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...) -> typing.Any: ...
def _lambertw(
    x1, x2, x3, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...
) -> typing.Any: ...
def _lanczos_sum_expg_scaled(
    x, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...
) -> typing.Any: ...
def _lgam1p(x, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...) -> typing.Any: ...
def _log1pmx(x, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...) -> typing.Any: ...
def _riemann_zeta(
    x, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...
) -> typing.Any: ...

_sf_error_action_map: dict
_sf_error_code_map: dict

def _sf_error_test_function(
    x, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...
) -> typing.Any: ...
def _sinpi(x, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...) -> typing.Any: ...
def _smirnovc(
    x1, x2, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...
) -> typing.Any: ...
def _smirnovci(
    x1, x2, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...
) -> typing.Any: ...
def _smirnovp(
    x1, x2, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...
) -> typing.Any: ...
def _spherical_in(
    x1, x2, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...
) -> typing.Any: ...
def _spherical_in_d(
    x1, x2, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...
) -> typing.Any: ...
def _spherical_jn(
    x1, x2, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...
) -> typing.Any: ...
def _spherical_jn_d(
    x1, x2, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...
) -> typing.Any: ...
def _spherical_kn(
    x1, x2, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...
) -> typing.Any: ...
def _spherical_kn_d(
    x1, x2, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...
) -> typing.Any: ...
def _spherical_yn(
    x1, x2, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...
) -> typing.Any: ...
def _spherical_yn_d(
    x1, x2, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...
) -> typing.Any: ...
def _struve_asymp_large_z(
    x1, x2, x3, out1=..., out2=..., out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...
) -> typing.Any: ...
def _struve_bessel_series(
    x1, x2, x3, out1=..., out2=..., out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...
) -> typing.Any: ...
def _struve_power_series(
    x1, x2, x3, out1=..., out2=..., out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...
) -> typing.Any: ...
def _zeta(
    x1, x2, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...
) -> typing.Any: ...
def agm(x1, x2, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...) -> typing.Any: ...
def airy(
    x,
    out1=...,
    out2=...,
    out3=...,
    out4=...,
    out=...,
    *,
    where=...,
    casting=...,
    order=...,
    dtype=...,
    subok=...,
    signature=...,
    extobj=...,
) -> typing.Any: ...
def airye(
    x,
    out1=...,
    out2=...,
    out3=...,
    out4=...,
    out=...,
    *,
    where=...,
    casting=...,
    order=...,
    dtype=...,
    subok=...,
    signature=...,
    extobj=...,
) -> typing.Any: ...
def bdtr(
    x1, x2, x3, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...
) -> typing.Any: ...
def bdtrc(
    x1, x2, x3, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...
) -> typing.Any: ...
def bdtri(
    x1, x2, x3, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...
) -> typing.Any: ...
def bdtrik(
    x1, x2, x3, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...
) -> typing.Any: ...
def bdtrin(
    x1, x2, x3, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...
) -> typing.Any: ...
def bei(x, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...) -> typing.Any: ...
def beip(x, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...) -> typing.Any: ...
def ber(x, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...) -> typing.Any: ...
def berp(x, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...) -> typing.Any: ...
def besselpoly(
    x1, x2, x3, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...
) -> typing.Any: ...
def beta(
    x1, x2, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...
) -> typing.Any: ...
def betainc(
    x1, x2, x3, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...
) -> typing.Any: ...
def betaincinv(
    x1, x2, x3, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...
) -> typing.Any: ...
def betaln(
    x1, x2, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...
) -> typing.Any: ...
def binom(
    x1, x2, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...
) -> typing.Any: ...
def boxcox(
    x1, x2, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...
) -> typing.Any: ...
def boxcox1p(
    x1, x2, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...
) -> typing.Any: ...
def btdtr(
    x1, x2, x3, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...
) -> typing.Any: ...
def btdtri(
    x1, x2, x3, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...
) -> typing.Any: ...
def btdtria(
    x1, x2, x3, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...
) -> typing.Any: ...
def btdtrib(
    x1, x2, x3, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...
) -> typing.Any: ...
def cbrt(x, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...) -> typing.Any: ...
def chdtr(
    x1, x2, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...
) -> typing.Any: ...
def chdtrc(
    x1, x2, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...
) -> typing.Any: ...
def chdtri(
    x1, x2, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...
) -> typing.Any: ...
def chdtriv(
    x1, x2, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...
) -> typing.Any: ...
def chndtr(
    x1, x2, x3, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...
) -> typing.Any: ...
def chndtridf(
    x1, x2, x3, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...
) -> typing.Any: ...
def chndtrinc(
    x1, x2, x3, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...
) -> typing.Any: ...
def chndtrix(
    x1, x2, x3, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...
) -> typing.Any: ...
def cosdg(x, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...) -> typing.Any: ...
def cosm1(x, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...) -> typing.Any: ...
def cotdg(x, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...) -> typing.Any: ...
def dawsn(x, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...) -> typing.Any: ...
def ellipe(x, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...) -> typing.Any: ...
def ellipeinc(
    x1, x2, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...
) -> typing.Any: ...
def ellipj(
    x1,
    x2,
    out1=...,
    out2=...,
    out3=...,
    out4=...,
    out=...,
    *,
    where=...,
    casting=...,
    order=...,
    dtype=...,
    subok=...,
    signature=...,
    extobj=...,
) -> typing.Any: ...
def ellipk(x, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...) -> typing.Any: ...
def ellipkinc(
    x1, x2, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...
) -> typing.Any: ...
def ellipkm1(x, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...) -> typing.Any: ...
def entr(x, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...) -> typing.Any: ...
def erf(x, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...) -> typing.Any: ...
def erfc(x, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...) -> typing.Any: ...
def erfcinv(x, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...) -> typing.Any: ...
def erfcx(x, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...) -> typing.Any: ...
def erfi(x, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...) -> typing.Any: ...
def erfinv(x, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...) -> typing.Any: ...

class errstate(_mod_builtins.object):
    __dict__: dict[str, typing.Any]
    def __enter__(self) -> typing.Any: ...
    def __exit__(self, exc_type, exc_value, traceback) -> typing.Any: ...
    def __init__(self, **kwargs) -> None: ...
    @classmethod
    def __init_subclass__(cls) -> None: ...
    __module__: str
    @classmethod
    def __subclasshook__(cls, subclass: typing.Any) -> bool: ...
    @property
    def __weakref__(self) -> typing.Any: ...
    def __getattr__(self, name) -> typing.Any: ...

def eval_chebyc(
    x1, x2, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...
) -> typing.Any: ...
def eval_chebys(
    x1, x2, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...
) -> typing.Any: ...
def eval_chebyt(
    x1, x2, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...
) -> typing.Any: ...
def eval_chebyu(
    x1, x2, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...
) -> typing.Any: ...
def eval_gegenbauer(
    x1, x2, x3, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...
) -> typing.Any: ...
def eval_genlaguerre(
    x1, x2, x3, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...
) -> typing.Any: ...
def eval_hermite(
    x1, x2, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...
) -> typing.Any: ...
def eval_hermitenorm(
    x1, x2, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...
) -> typing.Any: ...
def eval_jacobi(
    x1, x2, x3, x4, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...
) -> typing.Any: ...
def eval_laguerre(
    x1, x2, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...
) -> typing.Any: ...
def eval_legendre(
    x1, x2, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...
) -> typing.Any: ...
def eval_sh_chebyt(
    x1, x2, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...
) -> typing.Any: ...
def eval_sh_chebyu(
    x1, x2, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...
) -> typing.Any: ...
def eval_sh_jacobi(
    x1, x2, x3, x4, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...
) -> typing.Any: ...
def eval_sh_legendre(
    x1, x2, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...
) -> typing.Any: ...
def exp1(x, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...) -> typing.Any: ...
def exp10(x, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...) -> typing.Any: ...
def exp2(x, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...) -> typing.Any: ...
def expi(x, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...) -> typing.Any: ...
def expit(x, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...) -> typing.Any: ...
def expm1(x, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...) -> typing.Any: ...
def expn(
    x1, x2, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...
) -> typing.Any: ...
def exprel(x, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...) -> typing.Any: ...
def fdtr(
    x1, x2, x3, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...
) -> typing.Any: ...
def fdtrc(
    x1, x2, x3, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...
) -> typing.Any: ...
def fdtri(
    x1, x2, x3, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...
) -> typing.Any: ...
def fdtridfd(
    x1, x2, x3, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...
) -> typing.Any: ...
def fresnel(
    x, out1=..., out2=..., out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...
) -> typing.Any: ...
def gamma(x, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...) -> typing.Any: ...
def gammainc(
    x1, x2, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...
) -> typing.Any: ...
def gammaincc(
    x1, x2, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...
) -> typing.Any: ...
def gammainccinv(
    x1, x2, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...
) -> typing.Any: ...
def gammaincinv(
    x1, x2, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...
) -> typing.Any: ...
def gammaln(x, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...) -> typing.Any: ...
def gammasgn(x, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...) -> typing.Any: ...
def gdtr(
    x1, x2, x3, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...
) -> typing.Any: ...
def gdtrc(
    x1, x2, x3, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...
) -> typing.Any: ...
def gdtria(
    x1, x2, x3, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...
) -> typing.Any: ...
def gdtrib(
    x1, x2, x3, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...
) -> typing.Any: ...
def gdtrix(
    x1, x2, x3, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...
) -> typing.Any: ...
def geterr() -> typing.Any: ...
def hankel1(
    x1, x2, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...
) -> typing.Any: ...
def hankel1e(
    x1, x2, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...
) -> typing.Any: ...
def hankel2(
    x1, x2, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...
) -> typing.Any: ...
def hankel2e(
    x1, x2, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...
) -> typing.Any: ...
def huber(
    x1, x2, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...
) -> typing.Any: ...
def hyp0f1(
    x1, x2, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...
) -> typing.Any: ...
def hyp1f1(
    x1, x2, x3, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...
) -> typing.Any: ...
def hyp2f1(
    x1, x2, x3, x4, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...
) -> typing.Any: ...
def hyperu(
    x1, x2, x3, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...
) -> typing.Any: ...
def i0(x, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...) -> typing.Any: ...
def i0e(x, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...) -> typing.Any: ...
def i1(x, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...) -> typing.Any: ...
def i1e(x, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...) -> typing.Any: ...
def inv_boxcox(
    x1, x2, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...
) -> typing.Any: ...
def inv_boxcox1p(
    x1, x2, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...
) -> typing.Any: ...
def it2i0k0(
    x, out1=..., out2=..., out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...
) -> typing.Any: ...
def it2j0y0(
    x, out1=..., out2=..., out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...
) -> typing.Any: ...
def it2struve0(
    x, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...
) -> typing.Any: ...
def itairy(
    x,
    out1=...,
    out2=...,
    out3=...,
    out4=...,
    out=...,
    *,
    where=...,
    casting=...,
    order=...,
    dtype=...,
    subok=...,
    signature=...,
    extobj=...,
) -> typing.Any: ...
def iti0k0(
    x, out1=..., out2=..., out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...
) -> typing.Any: ...
def itj0y0(
    x, out1=..., out2=..., out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...
) -> typing.Any: ...
def itmodstruve0(
    x, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...
) -> typing.Any: ...
def itstruve0(
    x, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...
) -> typing.Any: ...
def iv(x1, x2, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...) -> typing.Any: ...
def ive(x1, x2, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...) -> typing.Any: ...
def j0(x, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...) -> typing.Any: ...
def j1(x, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...) -> typing.Any: ...
def jn(x1, x2, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...) -> typing.Any: ...
def jv(x1, x2, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...) -> typing.Any: ...
def jve(x1, x2, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...) -> typing.Any: ...
def k0(x, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...) -> typing.Any: ...
def k0e(x, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...) -> typing.Any: ...
def k1(x, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...) -> typing.Any: ...
def k1e(x, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...) -> typing.Any: ...
def kei(x, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...) -> typing.Any: ...
def keip(x, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...) -> typing.Any: ...
def kelvin(
    x,
    out1=...,
    out2=...,
    out3=...,
    out4=...,
    out=...,
    *,
    where=...,
    casting=...,
    order=...,
    dtype=...,
    subok=...,
    signature=...,
    extobj=...,
) -> typing.Any: ...
def ker(x, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...) -> typing.Any: ...
def kerp(x, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...) -> typing.Any: ...
def kl_div(
    x1, x2, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...
) -> typing.Any: ...
def kn(x1, x2, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...) -> typing.Any: ...
def kolmogi(x, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...) -> typing.Any: ...
def kolmogorov(
    x, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...
) -> typing.Any: ...
def kv(x1, x2, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...) -> typing.Any: ...
def kve(x1, x2, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...) -> typing.Any: ...
def log1p(x, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...) -> typing.Any: ...
def log_ndtr(x, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...) -> typing.Any: ...
def loggamma(x, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...) -> typing.Any: ...
def logit(x, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...) -> typing.Any: ...
def lpmv(
    x1, x2, x3, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...
) -> typing.Any: ...
def mathieu_a(
    x1, x2, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...
) -> typing.Any: ...
def mathieu_b(
    x1, x2, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...
) -> typing.Any: ...
def mathieu_cem(
    x1, x2, x3, out1=..., out2=..., out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...
) -> typing.Any: ...
def mathieu_modcem1(
    x1, x2, x3, out1=..., out2=..., out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...
) -> typing.Any: ...
def mathieu_modcem2(
    x1, x2, x3, out1=..., out2=..., out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...
) -> typing.Any: ...
def mathieu_modsem1(
    x1, x2, x3, out1=..., out2=..., out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...
) -> typing.Any: ...
def mathieu_modsem2(
    x1, x2, x3, out1=..., out2=..., out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...
) -> typing.Any: ...
def mathieu_sem(
    x1, x2, x3, out1=..., out2=..., out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...
) -> typing.Any: ...
def modfresnelm(
    x, out1=..., out2=..., out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...
) -> typing.Any: ...
def modfresnelp(
    x, out1=..., out2=..., out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...
) -> typing.Any: ...
def modstruve(
    x1, x2, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...
) -> typing.Any: ...
def nbdtr(
    x1, x2, x3, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...
) -> typing.Any: ...
def nbdtrc(
    x1, x2, x3, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...
) -> typing.Any: ...
def nbdtri(
    x1, x2, x3, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...
) -> typing.Any: ...
def nbdtrik(
    x1, x2, x3, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...
) -> typing.Any: ...
def nbdtrin(
    x1, x2, x3, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...
) -> typing.Any: ...
def ncfdtr(
    x1, x2, x3, x4, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...
) -> typing.Any: ...
def ncfdtri(
    x1, x2, x3, x4, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...
) -> typing.Any: ...
def ncfdtridfd(
    x1, x2, x3, x4, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...
) -> typing.Any: ...
def ncfdtridfn(
    x1, x2, x3, x4, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...
) -> typing.Any: ...
def ncfdtrinc(
    x1, x2, x3, x4, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...
) -> typing.Any: ...
def nctdtr(
    x1, x2, x3, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...
) -> typing.Any: ...
def nctdtridf(
    x1, x2, x3, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...
) -> typing.Any: ...
def nctdtrinc(
    x1, x2, x3, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...
) -> typing.Any: ...
def nctdtrit(
    x1, x2, x3, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...
) -> typing.Any: ...
def ndtr(x, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...) -> typing.Any: ...
def ndtri(x, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...) -> typing.Any: ...
def nrdtrimn(
    x1, x2, x3, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...
) -> typing.Any: ...
def nrdtrisd(
    x1, x2, x3, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...
) -> typing.Any: ...
def obl_ang1(
    x1,
    x2,
    x3,
    x4,
    out1=...,
    out2=...,
    out=...,
    *,
    where=...,
    casting=...,
    order=...,
    dtype=...,
    subok=...,
    signature=...,
    extobj=...,
) -> typing.Any: ...
def obl_ang1_cv(
    x1,
    x2,
    x3,
    x4,
    x5,
    out1=...,
    out2=...,
    out=...,
    *,
    where=...,
    casting=...,
    order=...,
    dtype=...,
    subok=...,
    signature=...,
    extobj=...,
) -> typing.Any: ...
def obl_cv(
    x1, x2, x3, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...
) -> typing.Any: ...
def obl_rad1(
    x1,
    x2,
    x3,
    x4,
    out1=...,
    out2=...,
    out=...,
    *,
    where=...,
    casting=...,
    order=...,
    dtype=...,
    subok=...,
    signature=...,
    extobj=...,
) -> typing.Any: ...
def obl_rad1_cv(
    x1,
    x2,
    x3,
    x4,
    x5,
    out1=...,
    out2=...,
    out=...,
    *,
    where=...,
    casting=...,
    order=...,
    dtype=...,
    subok=...,
    signature=...,
    extobj=...,
) -> typing.Any: ...
def obl_rad2(
    x1,
    x2,
    x3,
    x4,
    out1=...,
    out2=...,
    out=...,
    *,
    where=...,
    casting=...,
    order=...,
    dtype=...,
    subok=...,
    signature=...,
    extobj=...,
) -> typing.Any: ...
def obl_rad2_cv(
    x1,
    x2,
    x3,
    x4,
    x5,
    out1=...,
    out2=...,
    out=...,
    *,
    where=...,
    casting=...,
    order=...,
    dtype=...,
    subok=...,
    signature=...,
    extobj=...,
) -> typing.Any: ...
def owens_t(
    x1, x2, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...
) -> typing.Any: ...
def pbdv(
    x1, x2, out1=..., out2=..., out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...
) -> typing.Any: ...
def pbvv(
    x1, x2, out1=..., out2=..., out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...
) -> typing.Any: ...
def pbwa(
    x1, x2, out1=..., out2=..., out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...
) -> typing.Any: ...
def pdtr(
    x1, x2, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...
) -> typing.Any: ...
def pdtrc(
    x1, x2, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...
) -> typing.Any: ...
def pdtri(
    x1, x2, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...
) -> typing.Any: ...
def pdtrik(
    x1, x2, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...
) -> typing.Any: ...
def poch(
    x1, x2, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...
) -> typing.Any: ...
def pro_ang1(
    x1,
    x2,
    x3,
    x4,
    out1=...,
    out2=...,
    out=...,
    *,
    where=...,
    casting=...,
    order=...,
    dtype=...,
    subok=...,
    signature=...,
    extobj=...,
) -> typing.Any: ...
def pro_ang1_cv(
    x1,
    x2,
    x3,
    x4,
    x5,
    out1=...,
    out2=...,
    out=...,
    *,
    where=...,
    casting=...,
    order=...,
    dtype=...,
    subok=...,
    signature=...,
    extobj=...,
) -> typing.Any: ...
def pro_cv(
    x1, x2, x3, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...
) -> typing.Any: ...
def pro_rad1(
    x1,
    x2,
    x3,
    x4,
    out1=...,
    out2=...,
    out=...,
    *,
    where=...,
    casting=...,
    order=...,
    dtype=...,
    subok=...,
    signature=...,
    extobj=...,
) -> typing.Any: ...
def pro_rad1_cv(
    x1,
    x2,
    x3,
    x4,
    x5,
    out1=...,
    out2=...,
    out=...,
    *,
    where=...,
    casting=...,
    order=...,
    dtype=...,
    subok=...,
    signature=...,
    extobj=...,
) -> typing.Any: ...
def pro_rad2(
    x1,
    x2,
    x3,
    x4,
    out1=...,
    out2=...,
    out=...,
    *,
    where=...,
    casting=...,
    order=...,
    dtype=...,
    subok=...,
    signature=...,
    extobj=...,
) -> typing.Any: ...
def pro_rad2_cv(
    x1,
    x2,
    x3,
    x4,
    x5,
    out1=...,
    out2=...,
    out=...,
    *,
    where=...,
    casting=...,
    order=...,
    dtype=...,
    subok=...,
    signature=...,
    extobj=...,
) -> typing.Any: ...
def pseudo_huber(
    x1, x2, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...
) -> typing.Any: ...
def psi(x, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...) -> typing.Any: ...
def radian(
    x1, x2, x3, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...
) -> typing.Any: ...
def rel_entr(
    x1, x2, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...
) -> typing.Any: ...
def rgamma(x, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...) -> typing.Any: ...
def round(x, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...) -> typing.Any: ...
def seterr() -> typing.Any: ...
def shichi(
    x, out1=..., out2=..., out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...
) -> typing.Any: ...
def sici(
    x, out1=..., out2=..., out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...
) -> typing.Any: ...
def sindg(x, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...) -> typing.Any: ...
def smirnov(
    x1, x2, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...
) -> typing.Any: ...
def smirnovi(
    x1, x2, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...
) -> typing.Any: ...
def spence(x, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...) -> typing.Any: ...
def sph_harm(
    x1, x2, x3, x4, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...
) -> typing.Any: ...
def stdtr(
    x1, x2, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...
) -> typing.Any: ...
def stdtridf(
    x1, x2, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...
) -> typing.Any: ...
def stdtrit(
    x1, x2, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...
) -> typing.Any: ...
def struve(
    x1, x2, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...
) -> typing.Any: ...
def tandg(x, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...) -> typing.Any: ...
def tklmbda(
    x1, x2, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...
) -> typing.Any: ...
def voigt_profile(
    x1, x2, x3, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...
) -> typing.Any: ...
def wofz(x, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...) -> typing.Any: ...
def wrightomega(
    x, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...
) -> typing.Any: ...
def xlog1py(
    x1, x2, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...
) -> typing.Any: ...
def xlogy(
    x1, x2, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...
) -> typing.Any: ...
def y0(x, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...) -> typing.Any: ...
def y1(x, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...) -> typing.Any: ...
def yn(x1, x2, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...) -> typing.Any: ...
def yv(x1, x2, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...) -> typing.Any: ...
def yve(x1, x2, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...) -> typing.Any: ...
def zetac(x, out=..., *, where=..., casting=..., order=..., dtype=..., subok=..., signature=..., extobj=...) -> typing.Any: ...
def __getattr__(name) -> typing.Any: ...
