# Python: 3.8.2 (tags/v3.8.2:7b3ab59, Feb 25 2020, 23:03:10) [MSC v.1916 64 bit (AMD64)]
# Library: scipy, version: 1.6.2
# Module: scipy.special.cython_special, version: unspecified
import typing

__pyx_capi__: dict
__test__: dict

def _airy_pywrap(x0) -> typing.Any: ...
def _airye_pywrap(x0) -> typing.Any: ...
def _bench_airy_D_cy() -> typing.Any: ...
def _bench_airy_D_py() -> typing.Any: ...
def _bench_airy_d_cy() -> typing.Any: ...
def _bench_airy_d_py() -> typing.Any: ...
def _bench_beta_dd_cy() -> typing.Any: ...
def _bench_beta_dd_py() -> typing.Any: ...
def _bench_erf_D_cy() -> typing.Any: ...
def _bench_erf_D_py() -> typing.Any: ...
def _bench_erf_d_cy() -> typing.Any: ...
def _bench_erf_d_py() -> typing.Any: ...
def _bench_exprel_d_cy() -> typing.Any: ...
def _bench_exprel_d_py() -> typing.Any: ...
def _bench_gamma_D_cy() -> typing.Any: ...
def _bench_gamma_D_py() -> typing.Any: ...
def _bench_gamma_d_cy() -> typing.Any: ...
def _bench_gamma_d_py() -> typing.Any: ...
def _bench_jv_dD_cy() -> typing.Any: ...
def _bench_jv_dD_py() -> typing.Any: ...
def _bench_jv_dd_cy() -> typing.Any: ...
def _bench_jv_dd_py() -> typing.Any: ...
def _bench_loggamma_D_cy() -> typing.Any: ...
def _bench_loggamma_D_py() -> typing.Any: ...
def _bench_logit_d_cy() -> typing.Any: ...
def _bench_logit_d_py() -> typing.Any: ...
def _bench_psi_D_cy() -> typing.Any: ...
def _bench_psi_D_py() -> typing.Any: ...
def _bench_psi_d_cy() -> typing.Any: ...
def _bench_psi_d_py() -> typing.Any: ...
def _ellipj_pywrap() -> typing.Any: ...
def _fresnel_pywrap(x0) -> typing.Any: ...
def _it2i0k0_pywrap() -> typing.Any: ...
def _it2j0y0_pywrap() -> typing.Any: ...
def _itairy_pywrap() -> typing.Any: ...
def _iti0k0_pywrap() -> typing.Any: ...
def _itj0y0_pywrap() -> typing.Any: ...
def _kelvin_pywrap() -> typing.Any: ...
def _mathieu_cem_pywrap() -> typing.Any: ...
def _mathieu_modcem1_pywrap() -> typing.Any: ...
def _mathieu_modcem2_pywrap() -> typing.Any: ...
def _mathieu_modsem1_pywrap() -> typing.Any: ...
def _mathieu_modsem2_pywrap() -> typing.Any: ...
def _mathieu_sem_pywrap() -> typing.Any: ...
def _modfresnelm_pywrap() -> typing.Any: ...
def _modfresnelp_pywrap() -> typing.Any: ...
def _obl_ang1_cv_pywrap() -> typing.Any: ...
def _obl_ang1_pywrap() -> typing.Any: ...
def _obl_rad1_cv_pywrap() -> typing.Any: ...
def _obl_rad1_pywrap() -> typing.Any: ...
def _obl_rad2_cv_pywrap() -> typing.Any: ...
def _obl_rad2_pywrap() -> typing.Any: ...
def _pbdv_pywrap() -> typing.Any: ...
def _pbvv_pywrap() -> typing.Any: ...
def _pbwa_pywrap() -> typing.Any: ...
def _pro_ang1_cv_pywrap() -> typing.Any: ...
def _pro_ang1_pywrap() -> typing.Any: ...
def _pro_rad1_cv_pywrap() -> typing.Any: ...
def _pro_rad1_pywrap() -> typing.Any: ...
def _pro_rad2_cv_pywrap() -> typing.Any: ...
def _pro_rad2_pywrap() -> typing.Any: ...
def _shichi_pywrap(x0) -> typing.Any: ...
def _sici_pywrap(x0) -> typing.Any: ...
def agm() -> typing.Any: ...
def bdtr(x0, x1, x2) -> typing.Any: ...
def bdtrc(x0, x1, x2) -> typing.Any: ...
def bdtri(x0, x1, x2) -> typing.Any: ...
def bdtrik() -> typing.Any: ...
def bdtrin() -> typing.Any: ...
def bei() -> typing.Any: ...
def beip() -> typing.Any: ...
def ber() -> typing.Any: ...
def berp() -> typing.Any: ...
def besselpoly() -> typing.Any: ...
def beta() -> typing.Any: ...
def betainc() -> typing.Any: ...
def betaincinv() -> typing.Any: ...
def betaln() -> typing.Any: ...
def binom() -> typing.Any: ...
def boxcox() -> typing.Any: ...
def boxcox1p() -> typing.Any: ...
def btdtr() -> typing.Any: ...
def btdtri() -> typing.Any: ...
def btdtria() -> typing.Any: ...
def btdtrib() -> typing.Any: ...
def cbrt() -> typing.Any: ...
def chdtr() -> typing.Any: ...
def chdtrc() -> typing.Any: ...
def chdtri() -> typing.Any: ...
def chdtriv() -> typing.Any: ...
def chndtr() -> typing.Any: ...
def chndtridf() -> typing.Any: ...
def chndtrinc() -> typing.Any: ...
def chndtrix() -> typing.Any: ...
def cosdg() -> typing.Any: ...
def cosm1() -> typing.Any: ...
def cotdg() -> typing.Any: ...
def dawsn(x0) -> typing.Any: ...
def ellipe() -> typing.Any: ...
def ellipeinc() -> typing.Any: ...
def ellipk() -> typing.Any: ...
def ellipkinc() -> typing.Any: ...
def ellipkm1() -> typing.Any: ...
def entr() -> typing.Any: ...
def erf(x0) -> typing.Any: ...
def erfc(x0) -> typing.Any: ...
def erfcinv() -> typing.Any: ...
def erfcx(x0) -> typing.Any: ...
def erfi(x0) -> typing.Any: ...
def erfinv() -> typing.Any: ...
def eval_chebyc(x0, x1) -> typing.Any: ...
def eval_chebys(x0, x1) -> typing.Any: ...
def eval_chebyt(x0, x1) -> typing.Any: ...
def eval_chebyu(x0, x1) -> typing.Any: ...
def eval_gegenbauer(x0, x1, x2) -> typing.Any: ...
def eval_genlaguerre(x0, x1, x2) -> typing.Any: ...
def eval_hermite() -> typing.Any: ...
def eval_hermitenorm() -> typing.Any: ...
def eval_jacobi(x0, x1, x2, x3) -> typing.Any: ...
def eval_laguerre(x0, x1) -> typing.Any: ...
def eval_legendre(x0, x1) -> typing.Any: ...
def eval_sh_chebyt(x0, x1) -> typing.Any: ...
def eval_sh_chebyu(x0, x1) -> typing.Any: ...
def eval_sh_jacobi(x0, x1, x2, x3) -> typing.Any: ...
def eval_sh_legendre(x0, x1) -> typing.Any: ...
def exp1(x0) -> typing.Any: ...
def exp10() -> typing.Any: ...
def exp2() -> typing.Any: ...
def expi(x0) -> typing.Any: ...
def expit(x0) -> typing.Any: ...
def expm1(x0) -> typing.Any: ...
def expn(x0, x1) -> typing.Any: ...
def exprel() -> typing.Any: ...
def fdtr() -> typing.Any: ...
def fdtrc() -> typing.Any: ...
def fdtri() -> typing.Any: ...
def fdtridfd() -> typing.Any: ...
def gamma(x0) -> typing.Any: ...
def gammainc() -> typing.Any: ...
def gammaincc() -> typing.Any: ...
def gammainccinv() -> typing.Any: ...
def gammaincinv() -> typing.Any: ...
def gammaln() -> typing.Any: ...
def gammasgn() -> typing.Any: ...
def gdtr() -> typing.Any: ...
def gdtrc() -> typing.Any: ...
def gdtria() -> typing.Any: ...
def gdtrib() -> typing.Any: ...
def gdtrix() -> typing.Any: ...
def hankel1() -> typing.Any: ...
def hankel1e() -> typing.Any: ...
def hankel2() -> typing.Any: ...
def hankel2e() -> typing.Any: ...
def huber() -> typing.Any: ...
def hyp0f1(x0, x1) -> typing.Any: ...
def hyp1f1(x0, x1, x2) -> typing.Any: ...
def hyp2f1(x0, x1, x2, x3) -> typing.Any: ...
def hyperu() -> typing.Any: ...
def i0() -> typing.Any: ...
def i0e() -> typing.Any: ...
def i1() -> typing.Any: ...
def i1e() -> typing.Any: ...
def inv_boxcox() -> typing.Any: ...
def inv_boxcox1p() -> typing.Any: ...
def it2struve0() -> typing.Any: ...
def itmodstruve0() -> typing.Any: ...
def itstruve0() -> typing.Any: ...
def iv(x0, x1) -> typing.Any: ...
def ive(x0, x1) -> typing.Any: ...
def j0() -> typing.Any: ...
def j1() -> typing.Any: ...
def jv(x0, x1) -> typing.Any: ...
def jve(x0, x1) -> typing.Any: ...
def k0() -> typing.Any: ...
def k0e() -> typing.Any: ...
def k1() -> typing.Any: ...
def k1e() -> typing.Any: ...
def kei() -> typing.Any: ...
def keip() -> typing.Any: ...
def ker() -> typing.Any: ...
def kerp() -> typing.Any: ...
def kl_div() -> typing.Any: ...
def kn(x0, x1) -> typing.Any: ...
def kolmogi() -> typing.Any: ...
def kolmogorov() -> typing.Any: ...
def kv(x0, x1) -> typing.Any: ...
def kve(x0, x1) -> typing.Any: ...
def log1p(x0) -> typing.Any: ...
def log_ndtr(x0) -> typing.Any: ...
def loggamma(x0) -> typing.Any: ...
def logit(x0) -> typing.Any: ...
def lpmv() -> typing.Any: ...
def mathieu_a() -> typing.Any: ...
def mathieu_b() -> typing.Any: ...
def modstruve() -> typing.Any: ...
def nbdtr(x0, x1, x2) -> typing.Any: ...
def nbdtrc(x0, x1, x2) -> typing.Any: ...
def nbdtri(x0, x1, x2) -> typing.Any: ...
def nbdtrik() -> typing.Any: ...
def nbdtrin() -> typing.Any: ...
def ncfdtr() -> typing.Any: ...
def ncfdtri() -> typing.Any: ...
def ncfdtridfd() -> typing.Any: ...
def ncfdtridfn() -> typing.Any: ...
def ncfdtrinc() -> typing.Any: ...
def nctdtr() -> typing.Any: ...
def nctdtridf() -> typing.Any: ...
def nctdtrinc() -> typing.Any: ...
def nctdtrit() -> typing.Any: ...
def ndtr(x0) -> typing.Any: ...
def ndtri() -> typing.Any: ...
def nrdtrimn() -> typing.Any: ...
def nrdtrisd() -> typing.Any: ...
def obl_cv() -> typing.Any: ...
def owens_t() -> typing.Any: ...
def pdtr() -> typing.Any: ...
def pdtrc() -> typing.Any: ...
def pdtri(x0, x1) -> typing.Any: ...
def pdtrik() -> typing.Any: ...
def poch() -> typing.Any: ...
def pro_cv() -> typing.Any: ...
def pseudo_huber() -> typing.Any: ...
def psi(x0) -> typing.Any: ...
def radian() -> typing.Any: ...
def rel_entr() -> typing.Any: ...
def rgamma(x0) -> typing.Any: ...
def round() -> typing.Any: ...
def sindg() -> typing.Any: ...
def smirnov(x0, x1) -> typing.Any: ...
def smirnovi(x0, x1) -> typing.Any: ...
def spence(x0) -> typing.Any: ...
def sph_harm(x0, x1, x2, x3) -> typing.Any: ...
def spherical_in() -> typing.Any: ...
def spherical_jn() -> typing.Any: ...
def spherical_kn() -> typing.Any: ...
def spherical_yn() -> typing.Any: ...
def stdtr() -> typing.Any: ...
def stdtridf() -> typing.Any: ...
def stdtrit() -> typing.Any: ...
def struve() -> typing.Any: ...
def tandg() -> typing.Any: ...
def tklmbda() -> typing.Any: ...
def voigt_profile() -> typing.Any: ...
def wofz() -> typing.Any: ...
def wrightomega(x0) -> typing.Any: ...
def xlog1py(x0, x1) -> typing.Any: ...
def xlogy(x0, x1) -> typing.Any: ...
def y0() -> typing.Any: ...
def y1() -> typing.Any: ...
def yn(x0, x1) -> typing.Any: ...
def yv(x0, x1) -> typing.Any: ...
def yve(x0, x1) -> typing.Any: ...
def zetac() -> typing.Any: ...
def __getattr__(name) -> typing.Any: ...
