# Python: 3.8.2 (tags/v3.8.2:7b3ab59, Feb 25 2020, 23:03:10) [MSC v.1916 64 bit (AMD64)]
# Library: scipy, version: 1.6.2
# Module: scipy.special.specfun, version: $Revision: $
import typing

__version__: bytes

def airyzo(nt, kf=...) -> typing.Any: ...
def bernob(n) -> typing.Any: ...
def cerzo(nt) -> typing.Any: ...
def clpmn(m, n, x, y, ntype) -> typing.Any: ...
def clpn(n, z) -> typing.Any: ...
def clqmn(m, n, z) -> typing.Any: ...
def clqn(n, z) -> typing.Any: ...
def cpbdn(n, z) -> typing.Any: ...
def cyzo(nt, kf, kc) -> typing.Any: ...
def eulerb(n) -> typing.Any: ...
def fcoef(kd, m, q, a) -> typing.Any: ...
def fcszo(kf, nt) -> typing.Any: ...
def jdzo(nt) -> typing.Any: ...
def jyzo(n, nt) -> typing.Any: ...
def klvnzo(nt, kd) -> typing.Any: ...
def lamn(n, x) -> typing.Any: ...
def lamv(v, x) -> typing.Any: ...
def lpmn(m, n, x) -> typing.Any: ...
def lpn(n, x) -> typing.Any: ...
def lqmn(m, n, x) -> typing.Any: ...
def lqnb(n, x) -> typing.Any: ...
def pbdv(v, x) -> typing.Any: ...
def rctj(n, x) -> typing.Any: ...
def rcty(n, x) -> typing.Any: ...
def segv(m, n, c, kd) -> typing.Any: ...
def __getattr__(name) -> typing.Any: ...
