# Python: 3.8.2 (tags/v3.8.2:7b3ab59, Feb 25 2020, 23:03:10) [MSC v.1916 64 bit (AMD64)]
# Library: scipy, version: 1.6.2
# Module: scipy.integrate._dop, version: $Revision: $
import typing

__version__: bytes

def dop853(
    fcn, x, y, xend, rtol, atol, solout, iout, work, iwork, fcn_extra_args=..., overwrite_y=..., solout_extra_args=...
) -> typing.Any: ...
def dopri5(
    fcn, x, y, xend, rtol, atol, solout, iout, work, iwork, fcn_extra_args=..., overwrite_y=..., solout_extra_args=...
) -> typing.Any: ...
def types() -> typing.Any: ...
def __getattr__(name) -> typing.Any: ...
