# Python: 3.8.2 (tags/v3.8.2:7b3ab59, Feb 25 2020, 23:03:10) [MSC v.1916 64 bit (AMD64)]
# Library: scipy, version: 1.6.2
# Module: scipy.integrate._test_odeint_banded, version: $Revision: $
import typing

__version__: bytes

def banded5x5(t, y, f, n=...) -> typing.Any: ...
def banded5x5_bjac(t, y, ml, mu, bjac, n=..., nrowpd=...) -> typing.Any: ...
def banded5x5_jac(t, y, ml, mu, jac, n=..., nrowpd=...) -> typing.Any: ...
def banded5x5_solve(y, nsteps, dt, jt) -> typing.Any: ...
def getbands() -> typing.Any: ...
def jac() -> typing.Any: ...
def __getattr__(name) -> typing.Any: ...
