# Python: 3.8.2 (tags/v3.8.2:7b3ab59, Feb 25 2020, 23:03:10) [MSC v.1916 64 bit (AMD64)]
# Library: scipy, version: 1.6.2
# Module: scipy.integrate.lsoda, version: $Revision: $
import typing

__version__: bytes

def lsoda(
    f, y, t, tout, rtol, atol, itask, istate, rwork, iwork, jac, jt, f_extra_args=..., overwrite_y=..., jac_extra_args=...
) -> typing.Any: ...
def types() -> typing.Any: ...
def __getattr__(name) -> typing.Any: ...
