# Python: 3.8.2 (tags/v3.8.2:7b3ab59, Feb 25 2020, 23:03:10) [MSC v.1916 64 bit (AMD64)]
# Library: scipy, version: 1.6.2
# Module: scipy.integrate.vode, version: $Revision: $
import typing

__version__: bytes

def dvode(
    f, jac, y, t, tout, rtol, atol, itask, istate, rwork, iwork, mf, f_extra_args=..., jac_extra_args=..., overwrite_y=...
) -> typing.Any: ...
def types() -> typing.Any: ...
def zvode(
    f, jac, y, t, tout, rtol, atol, itask, istate, zwork, rwork, iwork, mf, f_extra_args=..., jac_extra_args=..., overwrite_y=...
) -> typing.Any: ...
def __getattr__(name) -> typing.Any: ...
