# Python: 3.8.2 (tags/v3.8.2:7b3ab59, Feb 25 2020, 23:03:10) [MSC v.1916 64 bit (AMD64)]
# Library: scipy, version: 1.6.2
# Module: scipy.optimize._zeros, version: unspecified
import typing

def _bisect() -> typing.Any: ...
def _brenth() -> typing.Any: ...
def _brentq() -> typing.Any: ...
def _ridder() -> typing.Any: ...
def __getattr__(name) -> typing.Any: ...
