# Python: 3.8.2 (tags/v3.8.2:7b3ab59, Feb 25 2020, 23:03:10) [MSC v.1916 64 bit (AMD64)]
# Library: scipy, version: 1.6.2
# Module: scipy.fftpack.convolve, version: unspecified
import typing

def __pyx_unpickle_Enum() -> typing.Any: ...

__test__: dict

def convolve(x, omega, swap_real_imag=..., overwrite_x=...) -> typing.Any: ...
def convolve_z(x, omega_real, omega_imag, overwrite_x=...) -> typing.Any: ...
def destroy_convolve_cache() -> typing.Any: ...
def init_convolution_kernel(n, kernel_func, d=..., zero_nyquist=..., kernel_func_extra_args=...) -> typing.Any: ...
def r2r_fftpack(a, axes, real2hermitian, forward, inorm=..., out=..., nthreads=...) -> typing.Any: ...
def __getattr__(name) -> typing.Any: ...
